name: Compilation test

on:
  push:

jobs:
  run-jpf:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8' ]
    name: Java ${{ matrix.java }} Run Compilation

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: fb4c49d917a493c8e4e8463df98438aafb38e5e8

    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Compile Java sources
      run: |
        ./gradlew clean build -x test
